export type AiringDay = "lunes" | "martes" | "miercoles" | "jueves" | "viernes" | "sabado" | "domingo";

export interface ExtendedAnime {
  malId: number;
  title: string;
  titleEnglish?: string;
  titleJapanese?: string;
  imageUrl: string;
  score: number;
  rank: number;
  episodes: number;
  status: string;
  season?: string;
  year?: number;
  studio: string;
  genres: string[];
  synopsis: string;
  watchedByFriends?: string[];
  airingDay?: AiringDay;
  broadcastTime?: string;
}

export interface StudioInfo {
  id: string;
  name: string;
  animeCount: number;
  popularAnime: string;
}

export interface UserFriendInfo {
  id: string;
  name: string;
  username: string;
  avatarUrl: string;
  role: string;
}

export const MOCK_STUDIOS: StudioInfo[] = [
  { id: "white-fox", name: "White Fox", animeCount: 14, popularAnime: "Steins;Gate, Re:Zero" },
  { id: "madhouse", name: "Madhouse", animeCount: 42, popularAnime: "Frieren, Hunter x Hunter, Death Note" },
  { id: "bones", name: "Bones", animeCount: 38, popularAnime: "Fullmetal Alchemist: Brotherhood, Mob Psycho 100" },
  { id: "mappa", name: "MAPPA", animeCount: 29, popularAnime: "Attack on Titan, Jujutsu Kaisen, Chainsaw Man" },
  { id: "ufotable", name: "ufotable", animeCount: 18, popularAnime: "Demon Slayer, Fate/Zero" },
  { id: "trigger", name: "Studio Trigger", animeCount: 15, popularAnime: "Cyberpunk: Edgerunners" },
  { id: "wit-studio", name: "Wit Studio", animeCount: 22, popularAnime: "Attack on Titan S1-S3, Vinland Saga S1" },
  { id: "kyoto-animation", name: "Kyoto Animation", animeCount: 31, popularAnime: "A Silent Voice, Violet Evergarden, Clannad" },
  { id: "cloverworks", name: "CloverWorks", animeCount: 20, popularAnime: "Bocchi the Rock!, Spy x Family, The Promised Neverland" },
  { id: "a1-pictures", name: "A-1 Pictures", animeCount: 45, popularAnime: "Solo Leveling, Kaguya-sama" },
];

export const MOCK_USER_FRIENDS: UserFriendInfo[] = [
  { id: "friend-1", name: "Sofía Martínez", username: "@otaku_queen", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150", role: "Amigo Otaku Elite" },
  { id: "friend-2", name: "Lucas Benítez", username: "@shonen_king", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150", role: "Especialista Sci-Fi" },
  { id: "friend-3", name: "Mauricio Rossi", username: "@seinen_fan", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150", role: "Critico de Anime" },
  { id: "friend-4", name: "Camila Torres", username: "@anime_vibes", avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150", role: "Coordinadora de Listas" },
];

export const MOCK_TOP_ANIMES: ExtendedAnime[] = [
  {
    malId: 52991,
    title: "Frieren: Beyond Journey's End",
    titleEnglish: "Frieren: Beyond Journey's End",
    titleJapanese: "葬送のフリーレン",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
    score: 9.34,
    rank: 1,
    episodes: 28,
    status: "Finalizado",
    season: "Otoño",
    year: 2023,
    studio: "Madhouse",
    genres: ["Fantasía", "Aventura", "Drama"],
    synopsis: "Tras la derrota del Rey Demonio a manos del grupo de héroes, la elfa Frieren reflexiona sobre su inmortalidad y emprende un nuevo viaje para comprender los sentimientos de sus compañeros humanos.",
    watchedByFriends: ["Sofía Martínez", "Mauricio Rossi", "Camila Torres"],
  },
  {
    malId: 5114,
    title: "Fullmetal Alchemist: Brotherhood",
    titleEnglish: "Fullmetal Alchemist: Brotherhood",
    titleJapanese: "鋼の錬金術師 FULLMETAL ALCHEMIST",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1208/94745.jpg",
    score: 9.10,
    rank: 2,
    episodes: 64,
    status: "Finalizado",
    season: "Primavera",
    year: 2009,
    studio: "Bones",
    genres: ["Acción", "Aventura", "Fantasía"],
    synopsis: "Edward y Alphonse Elric buscan la legendaria Piedra Filosofal tras sufrir graves mutilaciones en un intento fallido de transmutación humana para revivir a su madre.",
    watchedByFriends: ["Mauricio Rossi"],
  },
  {
    malId: 9253,
    title: "Steins;Gate",
    titleEnglish: "Steins;Gate",
    titleJapanese: "STEINS;GATE",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1935/127974.jpg",
    score: 9.07,
    rank: 3,
    episodes: 24,
    status: "Finalizado",
    season: "Primavera",
    year: 2011,
    studio: "White Fox",
    genres: ["Sci-Fi", "Psicológico", "Suspenso"],
    synopsis: "El científico excéntrico Rintarou Okabe y sus amigos descubren accidentalmente cómo enviar mensajes al pasado usando un microondas alterado, alterando las líneas de tiempo mundiales.",
    watchedByFriends: ["Sofía Martínez", "Lucas Benítez"],
  },
  {
    malId: 35760,
    title: "Attack on Titan Season 3 Part 2",
    titleEnglish: "Attack on Titan Season 3 Part 2",
    titleJapanese: "進撃の巨人 Season3 Part.2",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1517/100633.jpg",
    score: 9.05,
    rank: 4,
    episodes: 10,
    status: "Finalizado",
    season: "Primavera",
    year: 2019,
    studio: "Wit Studio",
    genres: ["Acción", "Fantasía", "Drama"],
    synopsis: "El Cuerpo de Exploración lucha contra los Titanes Colosal y Acorazado en la sangrienta operación para recuperar el Distrito Shiganshina y revelar el secreto del sótano.",
    watchedByFriends: ["Mauricio Rossi"],
  },
  {
    malId: 11061,
    title: "Hunter x Hunter (2011)",
    titleEnglish: "Hunter x Hunter",
    titleJapanese: "HUNTER×HUNTER（2011）",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1337/99013.jpg",
    score: 9.04,
    rank: 5,
    episodes: 148,
    status: "Finalizado",
    season: "Otoño",
    year: 2011,
    studio: "Madhouse",
    genres: ["Acción", "Aventura", "Fantasía"],
    synopsis: "Gon Freecss descubre que su padre está vivo y es un legendario Cazador. Gon decide tomar el letal examen de Cazador y emprender una travesía épica.",
    watchedByFriends: ["Mauricio Rossi", "Lucas Benítez"],
  },
  {
    malId: 28851,
    title: "A Silent Voice (Koe no Katachi)",
    titleEnglish: "A Silent Voice",
    titleJapanese: "聲の形",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1122/96444.jpg",
    score: 8.94,
    rank: 6,
    episodes: 1,
    status: "Película",
    season: "Otoño",
    year: 2016,
    studio: "Kyoto Animation",
    genres: ["Drama", "Slice of Life"],
    synopsis: "Shouya Ishida busca redimirse años después de haber acosado vilmente a Shouko Nishimiya, una niña sorda, durante su época en la escuela primaria.",
    watchedByFriends: ["Camila Torres"],
  },
  {
    malId: 4181,
    title: "Clannad: After Story",
    titleEnglish: "Clannad: After Story",
    titleJapanese: "CLANNAD 〜AFTER STORY〜",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1299/110774.jpg",
    score: 8.93,
    rank: 7,
    episodes: 24,
    status: "Finalizado",
    season: "Otoño",
    year: 2008,
    studio: "Kyoto Animation",
    genres: ["Drama", "Romance", "Slice of Life"],
    synopsis: "Tomoya y Nagisa comienzan su vida adulta juntos, enfrentando alegrías profundas y tragedias desgarradoras que pondrán a prueba su amor.",
    watchedByFriends: [],
  },
  {
    malId: 40028,
    title: "Attack on Titan Final Season",
    titleEnglish: "Attack on Titan Final Season",
    titleJapanese: "進撃の巨人 The Final Season",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1000/110531.jpg",
    score: 8.91,
    rank: 8,
    episodes: 16,
    status: "Finalizado",
    season: "Invierno",
    year: 2020,
    studio: "MAPPA",
    genres: ["Acción", "Fantasía", "Drama"],
    synopsis: "Gabi Braun y Falco Grice luchan por Marley mientras la guerra contra el imperio de Paradis estalla con el devastador ataque de Eren Jaeger.",
    watchedByFriends: ["Sofía Martínez", "Mauricio Rossi"],
  },
  {
    malId: 19,
    title: "Monster",
    titleEnglish: "Monster",
    titleJapanese: "MONSTER",
    imageUrl: "https://cdn.myanimelist.net/images/anime/10/18741.jpg",
    score: 8.88,
    rank: 9,
    episodes: 74,
    status: "Finalizado",
    season: "Primavera",
    year: 2004,
    studio: "Madhouse",
    genres: ["Suspenso", "Misterio", "Psicológico"],
    synopsis: "El dr. Kenzo Tenma salva la vida de un niño herido en lugar de un alcalde político. Años más tarde descubre que el niño se ha convertido en un frío asesino en serie.",
    watchedByFriends: ["Mauricio Rossi"],
  },
  {
    malId: 32281,
    title: "Your Name (Kimi no Na wa.)",
    titleEnglish: "Your Name.",
    titleJapanese: "君の名は。",
    imageUrl: "https://cdn.myanimelist.net/images/anime/5/87048.jpg",
    score: 8.84,
    rank: 10,
    episodes: 1,
    status: "Película",
    season: "Verano",
    year: 2016,
    studio: "CoMix Wave Films",
    genres: ["Romance", "Drama", "Sobrenatural"],
    synopsis: "Dos jóvenes desconocidos, Mitsuha y Taki, comienzan a intercambiar sus cuerpos inesperadamente, formando un vínculo a través del tiempo y el espacio.",
    watchedByFriends: ["Sofía Martínez", "Camila Torres"],
  },
  {
    malId: 49387,
    title: "Vinland Saga Season 2",
    titleEnglish: "Vinland Saga Season 2",
    titleJapanese: "ヴィンランド・サガ SEASON 2",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1170/124305.jpg",
    score: 8.80,
    rank: 11,
    episodes: 24,
    status: "Finalizado",
    season: "Invierno",
    year: 2023,
    studio: "MAPPA",
    genres: ["Drama", "Aventura"],
    synopsis: "Thorfinn se convierte en esclavo en Dinamarca buscando superar sus traumas pasados y aprender el valor verdadero de la no violencia.",
    watchedByFriends: ["Mauricio Rossi"],
  },
  {
    malId: 37510,
    title: "Mob Psycho 100 II",
    titleEnglish: "Mob Psycho 100 II",
    titleJapanese: "モブサイコ100 II",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1918/96303.jpg",
    score: 8.80,
    rank: 12,
    episodes: 13,
    status: "Finalizado",
    season: "Invierno",
    year: 2019,
    studio: "Bones",
    genres: ["Acción", "Comedia", "Sobrenatural"],
    synopsis: "Mob intenta equilibrar su vida escolar y sus inmensos poderes psíquicos mientras enfrenta amenazas cada vez más destructivas.",
    watchedByFriends: ["Camila Torres"],
  },
  {
    malId: 48569,
    title: "Jujutsu Kaisen Season 2",
    titleEnglish: "Jujutsu Kaisen Season 2",
    titleJapanese: "呪術廻戦 第2期",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1693/138407.jpg",
    score: 8.79,
    rank: 13,
    episodes: 23,
    status: "Finalizado",
    season: "Verano",
    year: 2023,
    studio: "MAPPA",
    genres: ["Acción", "Fantasía", "Suspenso"],
    synopsis: "Explora la juventud de Satoru Gojo y Suguru Geto, seguida por el trágico e inmenso despliegue del Incidente de Shibuya.",
    watchedByFriends: ["Lucas Benítez", "Mauricio Rossi"],
  },
  {
    malId: 50709,
    title: "Bocchi the Rock!",
    titleEnglish: "Bocchi the Rock!",
    titleJapanese: "ぼっち・ざ・ろっく！",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1448/127956.jpg",
    score: 8.78,
    rank: 14,
    episodes: 12,
    status: "Finalizado",
    season: "Otoño",
    year: 2022,
    studio: "CloverWorks",
    genres: ["Comedia", "Música", "Slice of Life"],
    synopsis: "Hitori Gotou es una guitarrista talentosa pero sumamente tímida que sueña con tocar en una banda de rock y superar su ansiedad social.",
    watchedByFriends: [],
  },
  {
    malId: 199,
    title: "El Viaje de Chihiro (Spirited Away)",
    titleEnglish: "Spirited Away",
    titleJapanese: "千と千尋の神隠し",
    imageUrl: "https://cdn.myanimelist.net/images/anime/6/79597.jpg",
    score: 8.77,
    rank: 15,
    episodes: 1,
    status: "Película",
    season: "Verano",
    year: 2001,
    studio: "Studio Ghibli",
    genres: ["Fantasía", "Aventura"],
    synopsis: "Chihiro atrapada en un mundo de dioses y espíritus debe trabajar en la casa de baños mágicos para liberar a sus padres.",
    watchedByFriends: ["Sofía Martínez"],
  },
  {
    malId: 1,
    title: "Cowboy Bebop",
    titleEnglish: "Cowboy Bebop",
    titleJapanese: "カウボーイビバップ",
    imageUrl: "https://cdn.myanimelist.net/images/anime/4/19644.jpg",
    score: 8.75,
    rank: 16,
    episodes: 26,
    status: "Finalizado",
    season: "Primavera",
    year: 1998,
    studio: "Sunrise",
    genres: ["Sci-Fi", "Acción", "Drama"],
    synopsis: "Spike Spiegel y Jet Black persiguen criminales espaciales a bordo de la nave Bebop mientras su propio pasado los alcanza.",
    watchedByFriends: ["Sofía Martínez", "Mauricio Rossi"],
  },
  {
    malId: 37521,
    title: "Vinland Saga Season 1",
    titleEnglish: "Vinland Saga Season 1",
    titleJapanese: "ヴィンランド・サガ",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1500/103000.jpg",
    score: 8.73,
    rank: 17,
    episodes: 24,
    status: "Finalizado",
    season: "Verano",
    year: 2019,
    studio: "Wit Studio",
    genres: ["Acción", "Aventura", "Drama"],
    synopsis: "Thorfinn se une al grupo mercenario de Askeladd para vengar la muerte de su padre Thors en un duelo a muerte honorable.",
    watchedByFriends: ["Mauricio Rossi"],
  },
  {
    malId: 1575,
    title: "Code Geass: Lelouch of the Rebellion",
    titleEnglish: "Code Geass: Lelouch of the Rebellion",
    titleJapanese: "コードギアス 反逆のルルーシュ",
    imageUrl: "https://cdn.myanimelist.net/images/anime/5/50331.jpg",
    score: 8.70,
    rank: 18,
    episodes: 25,
    status: "Finalizado",
    season: "Otoño",
    year: 2006,
    studio: "Sunrise",
    genres: ["Mecha", "Sci-Fi", "Suspenso"],
    synopsis: "Lelouch vi Britannia recibe el poder del Geass y asume la identidad de Zero para destruir al Imperio de Britannia.",
    watchedByFriends: ["Sofía Martínez"],
  },
  {
    malId: 34599,
    title: "Made in Abyss",
    titleEnglish: "Made in Abyss",
    titleJapanese: "メイドインアビス",
    imageUrl: "https://cdn.myanimelist.net/images/anime/6/86733.jpg",
    score: 8.67,
    rank: 19,
    episodes: 13,
    status: "Finalizado",
    season: "Verano",
    year: 2017,
    studio: "Kinema Citrus",
    genres: ["Aventura", "Fantasía", "Suspenso"],
    synopsis: "Riko y el robot Reg se aventuran en el abismo gigante infinito en busca de la madre de Riko enfrentando criaturas horripilantes.",
    watchedByFriends: [],
  },
  {
    malId: 1535,
    title: "Death Note",
    titleEnglish: "Death Note",
    titleJapanese: "DEATH NOTE",
    imageUrl: "https://cdn.myanimelist.net/images/anime/9/9444.jpg",
    score: 8.62,
    rank: 20,
    episodes: 37,
    status: "Finalizado",
    season: "Otoño",
    year: 2006,
    studio: "Madhouse",
    genres: ["Misterio", "Suspenso", "Psicológico"],
    synopsis: "Light Yagami encuentra un cuaderno de la muerte y decide purgar el mundo de criminales bajo el alias Kira, desatando el duelo mental contra L.",
    watchedByFriends: ["Sofía Martínez", "Lucas Benítez"],
  },
  {
    malId: 40748,
    title: "Jujutsu Kaisen",
    titleEnglish: "Jujutsu Kaisen",
    titleJapanese: "呪術廻戦",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    score: 8.61,
    rank: 21,
    episodes: 24,
    status: "Finalizado",
    season: "Otoño",
    year: 2020,
    studio: "MAPPA",
    genres: ["Acción", "Fantasía", "Suspenso"],
    synopsis: "Yuji Itadori se traga un objeto maldito de Ryomen Sukuna y entra en la escuela de Hechiceros de Tokio para recolectar todos los dedos.",
    watchedByFriends: ["Lucas Benítez"],
  },
  {
    malId: 42310,
    title: "Cyberpunk: Edgerunners",
    titleEnglish: "Cyberpunk: Edgerunners",
    titleJapanese: "サイバーパンク エッジランナーズ",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1818/126436.jpg",
    score: 8.60,
    rank: 22,
    episodes: 10,
    status: "Finalizado",
    season: "Otoño",
    year: 2022,
    studio: "Studio Trigger",
    genres: ["Cyberpunk", "Acción", "Sci-Fi"],
    synopsis: "David Martinez se instala un ciberware militar letal tras una tragedia y entra al bajo mundo de Night City como un Edgerunner.",
    watchedByFriends: ["Lucas Benítez"],
  },
  {
    malId: 47778,
    title: "Kimetsu no Yaiba: Mugen Train Arc",
    titleEnglish: "Demon Slayer: Mugen Train Arc",
    titleJapanese: "鬼滅の刃 無限列車編",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1764/116634.jpg",
    score: 8.55,
    rank: 23,
    episodes: 7,
    status: "Finalizado",
    season: "Otoño",
    year: 2021,
    studio: "ufotable",
    genres: ["Acción", "Fantasía"],
    synopsis: "Tanjiro y Kyojuro Rengoku luchan a bordo del Tren Infinito contra un demonio de la Luna Inferior.",
    watchedByFriends: [],
  },
  {
    malId: 16498,
    title: "Attack on Titan Season 1",
    titleEnglish: "Attack on Titan Season 1",
    titleJapanese: "進撃の巨人",
    imageUrl: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    score: 8.54,
    rank: 24,
    episodes: 25,
    status: "Finalizado",
    season: "Primavera",
    year: 2013,
    studio: "Wit Studio",
    genres: ["Acción", "Fantasía", "Drama"],
    synopsis: "La humanidad se refugia tras muros gigantescos hasta que un Titán Colosal destruye el distrito exterior de Eren Jaeger.",
    watchedByFriends: ["Mauricio Rossi", "Sofía Martínez"],
  },
  {
    malId: 35180,
    title: "Steins;Gate 0",
    titleEnglish: "Steins;Gate 0",
    titleJapanese: "シュタインズ・ゲート ゼロ",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1375/93837.jpg",
    score: 8.52,
    rank: 25,
    episodes: 23,
    status: "Finalizado",
    season: "Primavera",
    year: 2018,
    studio: "White Fox",
    genres: ["Sci-Fi", "Suspenso", "Drama"],
    synopsis: "En una línea de universo Beta, Okabe sufre trauma emocional y se vincula a una Inteligencia Artificial con los recuerdos de Kurisu.",
    watchedByFriends: ["Lucas Benítez"],
  },
  {
    malId: 37779,
    title: "The Promised Neverland Season 1",
    titleEnglish: "The Promised Neverland",
    titleJapanese: "約束のネバーランド",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1125/96929.jpg",
    score: 8.52,
    rank: 26,
    episodes: 12,
    status: "Finalizado",
    season: "Invierno",
    year: 2019,
    studio: "CloverWorks",
    genres: ["Misterio", "Suspenso", "Psicológico"],
    synopsis: "Tres niños superdotados en un orfanato descubren que están siendo criados como alimento para demonios.",
    watchedByFriends: [],
  },
  {
    malId: 50265,
    title: "Spy x Family",
    titleEnglish: "Spy x Family",
    titleJapanese: "SPY×FAMILY",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1441/122795.jpg",
    score: 8.52,
    rank: 27,
    episodes: 12,
    status: "Finalizado",
    season: "Primavera",
    year: 2022,
    studio: "WIT Studio & CloverWorks",
    genres: ["Acción", "Comedia"],
    synopsis: "El espía Twilight crea la familia Forger con una niña telépata y una asesina a sueldo sin saber sus verdaderas identidades.",
    watchedByFriends: ["Sofía Martínez", "Camila Torres"],
  },
  {
    malId: 44511,
    title: "Chainsaw Man",
    titleEnglish: "Chainsaw Man",
    titleJapanese: "チェンソーマン",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg",
    score: 8.51,
    rank: 28,
    episodes: 12,
    status: "Finalizado",
    season: "Otoño",
    year: 2022,
    studio: "MAPPA",
    genres: ["Acción", "Fantasía", "Suspenso"],
    synopsis: "Denji revive al fusionarse con su perro demonio Mochita transformándose en el motosierra viviente.",
    watchedByFriends: ["Lucas Benítez", "Camila Torres"],
  },
  {
    malId: 30276,
    title: "One Punch Man",
    titleEnglish: "One Punch Man",
    titleJapanese: "ワンパンマン",
    imageUrl: "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
    score: 8.50,
    rank: 29,
    episodes: 12,
    status: "Finalizado",
    season: "Otoño",
    year: 2015,
    studio: "Madhouse",
    genres: ["Acción", "Comedia", "Sci-Fi"],
    synopsis: "Saitama entrenó tanto que venció a cualquier monstruo de un solo puñetazo, cayendo en el aburrimiento.",
    watchedByFriends: ["Lucas Benítez", "Sofía Martínez"],
  },
  {
    malId: 38000,
    title: "Demon Slayer: Kimetsu no Yaiba",
    titleEnglish: "Demon Slayer: Kimetsu no Yaiba",
    titleJapanese: "鬼滅の刃",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
    score: 8.49,
    rank: 30,
    episodes: 26,
    status: "Finalizado",
    season: "Primavera",
    year: 2019,
    studio: "ufotable",
    genres: ["Acción", "Fantasía", "Aventura"],
    synopsis: "Tanjiro Kamado se empuña la espada de cazador para devolverle la humanidad a su hermana Nezuko.",
    watchedByFriends: ["Camila Torres"],
  },
  {
    malId: 32182,
    title: "Mob Psycho 100",
    titleEnglish: "Mob Psycho 100",
    titleJapanese: "モブサイコ100",
    imageUrl: "https://cdn.myanimelist.net/images/anime/8/80356.jpg",
    score: 8.48,
    rank: 31,
    episodes: 12,
    status: "Finalizado",
    season: "Verano",
    year: 2016,
    studio: "Bones",
    genres: ["Acción", "Comedia", "Sobrenatural"],
    synopsis: "Shigeo Kageyama libera poder psíquico colosal cuando sus emociones estallan al 100%.",
    watchedByFriends: ["Camila Torres"],
  },
  {
    malId: 20583,
    title: "Haikyuu!!",
    titleEnglish: "Haikyu!!",
    titleJapanese: "ハイキュー!!",
    imageUrl: "https://cdn.myanimelist.net/images/anime/7/76014.jpg",
    score: 8.44,
    rank: 32,
    episodes: 25,
    status: "Finalizado",
    season: "Primavera",
    year: 2014,
    studio: "Production I.G",
    genres: ["Deportes", "Comedia", "Drama"],
    synopsis: "Hinata Shoyo compensa su baja estatura con un salto explosivo al unirse al equipo de voleibol de Karasuno.",
    watchedByFriends: ["Camila Torres"],
  },
  {
    malId: 37991,
    title: "Kaguya-sama: Love is War",
    titleEnglish: "Kaguya-sama: Love is War",
    titleJapanese: "かぐや様は告らせたい",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1295/106551.jpg",
    score: 8.40,
    rank: 33,
    episodes: 12,
    status: "Finalizado",
    season: "Invierno",
    year: 2019,
    studio: "A-1 Pictures",
    genres: ["Comedia", "Romance", "Slice of Life"],
    synopsis: "Miyuki Shirogane y Kaguya Shinomiya usan juegos psicológicos para que el otro admita su amor primero.",
    watchedByFriends: [],
  },
  {
    malId: 39530,
    title: "Mushoku Tensei: Jobless Reincarnation",
    titleEnglish: "Mushoku Tensei: Jobless Reincarnation",
    titleJapanese: "無職転生 ～異世界行ったら本気だす～",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1530/117776.jpg",
    score: 8.36,
    rank: 34,
    episodes: 11,
    status: "Finalizado",
    season: "Invierno",
    year: 2021,
    studio: "Studio Bind",
    genres: ["Isekai", "Fantasía", "Aventura"],
    synopsis: "Rudeus Greyrat aprovecha su segunda oportunidad en un mundo de magia para dominar el arte de los hechizos.",
    watchedByFriends: [],
  },
  {
    malId: 30,
    title: "Neon Genesis Evangelion",
    titleEnglish: "Neon Genesis Evangelion",
    titleJapanese: "新世紀エヴァンゲリオン",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1314/108941.jpg",
    score: 8.35,
    rank: 35,
    episodes: 26,
    status: "Finalizado",
    season: "Otoño",
    year: 1995,
    studio: "Gainax",
    genres: ["Mecha", "Sci-Fi", "Psicológico"],
    synopsis: "Shinji Ikari debe pilotar el EVA-01 en Tokyo-3 enfrentando a los seres conocidos como Ángeles.",
    watchedByFriends: ["Lucas Benítez"],
  },
  {
    malId: 52299,
    title: "Solo Leveling",
    titleEnglish: "Solo Leveling",
    titleJapanese: "俺だけレベルアップな件",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1183/140733.jpg",
    score: 8.35,
    rank: 36,
    episodes: 12,
    status: "Finalizado",
    season: "Invierno",
    year: 2024,
    studio: "A-1 Pictures",
    genres: ["Acción", "Fantasía"],
    synopsis: "Sung Jinwoo renace como el único cazador capaz de subir de nivel sin límites gracias a un misterioso sistema de misiones.",
    watchedByFriends: ["Lucas Benítez"],
  },
  {
    malId: 22535,
    title: "Parasyte -the maxim-",
    titleEnglish: "Parasyte -the maxim-",
    titleJapanese: "寄生獣 セイの格率",
    imageUrl: "https://cdn.myanimelist.net/images/anime/5/73178.jpg",
    score: 8.33,
    rank: 37,
    episodes: 24,
    status: "Finalizado",
    season: "Otoño",
    year: 2014,
    studio: "Madhouse",
    genres: ["Acción", "Sci-Fi", "Suspenso"],
    synopsis: "Shinichi Izumi aliase con Migi, la criatura alienígena que habita en su brazo derecho, para detener parásitos voraces.",
    watchedByFriends: [],
  },
  {
    malId: 13601,
    title: "Psycho-Pass",
    titleEnglish: "Psycho-Pass",
    titleJapanese: "PSYCHO-PASS サイコパス",
    imageUrl: "https://cdn.myanimelist.net/images/anime/5/43399.jpg",
    score: 8.33,
    rank: 38,
    episodes: 22,
    status: "Finalizado",
    season: "Otoño",
    year: 2012,
    studio: "Production I.G",
    genres: ["Sci-Fi", "Suspenso", "Cyberpunk"],
    synopsis: "La inspectora Akane Tsunemori investiga crímenes en un Japón gobernado por el omnisciente Sistema Sibyl.",
    watchedByFriends: ["Lucas Benítez"],
  },
  {
    malId: 31043,
    title: "Erased (Boku dake ga Inai Machi)",
    titleEnglish: "ERASED",
    titleJapanese: "僕だけがいない街",
    imageUrl: "https://cdn.myanimelist.net/images/anime/10/77957.jpg",
    score: 8.30,
    rank: 39,
    episodes: 12,
    status: "Finalizado",
    season: "Invierno",
    year: 2016,
    studio: "A-1 Pictures",
    genres: ["Misterio", "Suspenso", "Sobrenatural"],
    synopsis: "Satoru viaja 18 años al pasado para evitar el secuestro y asesinato de su compañera Kayo Hinazuki.",
    watchedByFriends: [],
  },
  {
    malId: 38691,
    title: "Dr. STONE",
    titleEnglish: "Dr. STONE",
    titleJapanese: "Dr.STONE",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1764/101047.jpg",
    score: 8.28,
    rank: 40,
    episodes: 24,
    status: "Finalizado",
    season: "Verano",
    year: 2019,
    studio: "TMS Entertainment",
    genres: ["Sci-Fi", "Aventura"],
    synopsis: "Senku Ishigami usa la ciencia química y física para despertar a la humanidad de 3,700 años de petrificación.",
    watchedByFriends: [],
  },
  {
    malId: 10087,
    title: "Fate/Zero",
    titleEnglish: "Fate/Zero",
    titleJapanese: "Fate/Zero",
    imageUrl: "https://cdn.myanimelist.net/images/anime/2/33949.jpg",
    score: 8.28,
    rank: 41,
    episodes: 13,
    status: "Finalizado",
    season: "Otoño",
    year: 2011,
    studio: "ufotable",
    genres: ["Acción", "Fantasía"],
    synopsis: "Kiritsugu Emiya lucha en la sangrienta Cuarta Guerra del Santo Grial representando a la familia Einzbern.",
    watchedByFriends: [],
  },
  {
    malId: 33050,
    title: "KonoSuba Season 2",
    titleEnglish: "KonoSuba Season 2",
    titleJapanese: "この素晴らしい世界に祝福を！2",
    imageUrl: "https://cdn.myanimelist.net/images/anime/8/83617.jpg",
    score: 8.26,
    rank: 42,
    episodes: 10,
    status: "Finalizado",
    season: "Invierno",
    year: 2017,
    studio: "Studio Deen",
    genres: ["Isekai", "Comedia", "Fantasía"],
    synopsis: "Kazuma, Aqua, Megumin y Darkness causan estragos cómicos mientras intentan pagar deudas en Axel.",
    watchedByFriends: [],
  },
  {
    malId: 31240,
    title: "Re:Zero − Starting Life in Another World",
    titleEnglish: "Re:ZERO -Starting Life in Another World-",
    titleJapanese: "Re:ゼロから始める異世界生活",
    imageUrl: "https://cdn.myanimelist.net/images/anime/11/79410.jpg",
    score: 8.24,
    rank: 43,
    episodes: 25,
    status: "Finalizado",
    season: "Primavera",
    year: 2016,
    studio: "White Fox",
    genres: ["Isekai", "Suspenso", "Fantasía"],
    synopsis: "Subaru Natsuki usa su dolorosa habilidad de 'Regreso por Muerte' para proteger a la media elfa Emilia.",
    watchedByFriends: ["Camila Torres"],
  },
  {
    malId: 37520,
    title: "Dororo",
    titleEnglish: "Dororo",
    titleJapanese: "どろろ",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1779/98670.jpg",
    score: 8.24,
    rank: 44,
    episodes: 24,
    status: "Finalizado",
    season: "Invierno",
    year: 2019,
    studio: "MAPPA & Tezuka Productions",
    genres: ["Acción", "Sobrenatural", "Fantasía"],
    synopsis: "Hyakkimaru recorre el Japón feudal derrotando demonios para recuperar sus órganos y prótesis robadas.",
    watchedByFriends: [],
  },
  {
    malId: 37450,
    title: "Rascal Does Not Dream of Bunny Girl Senpai",
    titleEnglish: "Rascal Does Not Dream of Bunny Girl Senpai",
    titleJapanese: "青春ブタ野郎はバニーガール先輩の夢を見ない",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1301/93586.jpg",
    score: 8.24,
    rank: 45,
    episodes: 13,
    status: "Finalizado",
    season: "Otoño",
    year: 2018,
    studio: "CloverWorks",
    genres: ["Drama", "Romance", "Sobrenatural"],
    synopsis: "Sakuta Azusagawa ayuda a estudiantes que sufren anomalías físicas provocadas por el Síndrome de la Pubertad.",
    watchedByFriends: [],
  },
  {
    malId: 22297,
    title: "Fate/stay night: Unlimited Blade Works",
    titleEnglish: "Fate/stay night: Unlimited Blade Works",
    titleJapanese: "Fate/stay night [Unlimited Blade Works]",
    imageUrl: "https://cdn.myanimelist.net/images/anime/12/75199.jpg",
    score: 8.19,
    rank: 46,
    episodes: 12,
    status: "Finalizado",
    season: "Otoño",
    year: 2014,
    studio: "ufotable",
    genres: ["Acción", "Fantasía"],
    synopsis: "Shirou Emiya y Rin Tohsaka unen fuerzas con Saber y Archer en la batalla por el Grial.",
    watchedByFriends: [],
  },
  {
    malId: 28223,
    title: "Death Parade",
    titleEnglish: "Death Parade",
    titleJapanese: "デス・パレード",
    imageUrl: "https://cdn.myanimelist.net/images/anime/5/71553.jpg",
    score: 8.15,
    rank: 47,
    episodes: 12,
    status: "Finalizado",
    season: "Invierno",
    year: 2015,
    studio: "Madhouse",
    genres: ["Suspenso", "Sobrenatural", "Psicológico"],
    synopsis: "El barmen Decim desafía las almas recién fallecidas a juegos arbitrarios para decidir la reencarnación o el vacío.",
    watchedByFriends: [],
  },
  {
    malId: 37430,
    title: "That Time I Got Reincarnated as a Slime",
    titleEnglish: "That Time I Got Reincarnated as a Slime",
    titleJapanese: "転生したらスライムだった件",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1505/95217.jpg",
    score: 8.12,
    rank: 48,
    episodes: 24,
    status: "Finalizado",
    season: "Otoño",
    year: 2018,
    studio: "8bit",
    genres: ["Isekai", "Fantasía", "Aventura"],
    synopsis: "Rimuru Tempest funda la Federación Jura Tempest acogiendo a todas las razas mágicas del bosque.",
    watchedByFriends: [],
  },
  {
    malId: 33486,
    title: "My Hero Academia Season 2",
    titleEnglish: "My Hero Academia Season 2",
    titleJapanese: "僕のヒーローアカデミア",
    imageUrl: "https://cdn.myanimelist.net/images/anime/12/85221.jpg",
    score: 8.10,
    rank: 49,
    episodes: 25,
    status: "Finalizado",
    season: "Primavera",
    year: 2017,
    studio: "Bones",
    genres: ["Acción", "Fantasía"],
    synopsis: "Izuku Midoriya saca el poder de One For All durante el gran Festival Deportivo de la UA.",
    watchedByFriends: [],
  },
  {
    malId: 19815,
    title: "No Game No Life",
    titleEnglish: "No Game No Life",
    titleJapanese: "ノーゲーム・ノーライフ",
    imageUrl: "https://cdn.myanimelist.net/images/anime/1074/111944.jpg",
    score: 8.08,
    rank: 50,
    episodes: 12,
    status: "Finalizado",
    season: "Primavera",
    year: 2014,
    studio: "Madhouse",
    genres: ["Isekai", "Fantasía", "Comedia"],
    synopsis: "Sora y Shiro son transportados a Disboard, un mundo donde la violencia está prohibida y el juego decide los reinos.",
    watchedByFriends: [],
  },
];
